# Generated by Django 4.2.11 on 2024-05-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='questions',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
