# Generated by Django 4.2.11 on 2024-05-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_exams_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='answers',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='exams',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='context',
            name='data',
            field=models.CharField(max_length=100000),
        ),
    ]
